version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
  backend:
    build: ./backend
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
      CORS_ORIGIN: ${CORS_ORIGIN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CACHE_TTL_DAYS: ${CACHE_TTL_DAYS}
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
  dashboard:
    build: ./dashboard
    env_file: .env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports: ["3000:3000"]
    depends_on: [backend]
volumes:
  db_data:
